//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.Features.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hermes.Features.Settings.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de resplado de entrada.
        /// </summary>
        internal static string Backup_Input_Path {
            get {
                return ResourceManager.GetString("Backup Input Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de resplado de trazabilidad.
        /// </summary>
        internal static string Backup_SFC_Path {
            get {
                return ResourceManager.GetString("Backup SFC Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Bool Field.
        /// </summary>
        internal static string Bool_Field {
            get {
                return ResourceManager.GetString("Bool Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Browser Field.
        /// </summary>
        internal static string Browser_Field {
            get {
                return ResourceManager.GetString("Browser Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown.
        /// </summary>
        internal static string Dropdown {
            get {
                return ResourceManager.GetString("Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the string field equals to the selected option text.
        /// </summary>
        internal static string Dropdown_Description_1 {
            get {
                return ResourceManager.GetString("Dropdown Description 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the string field equals to the value of the selected KeyValuePair: Option A (A), Option B (B), Option C (C).
        /// </summary>
        internal static string Dropdown_Description_2 {
            get {
                return ResourceManager.GetString("Dropdown Description 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the integer field equals to the value of the selected KeyValuePair: Slow (10), Medium (50), Fast (100).
        /// </summary>
        internal static string Dropdown_Description_3 {
            get {
                return ResourceManager.GetString("Dropdown Description 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Dropdown Field.
        /// </summary>
        internal static string Dropdown_Field {
            get {
                return ResourceManager.GetString("Dropdown Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Dropdown Field 2.
        /// </summary>
        internal static string Dropdown_Field_2 {
            get {
                return ResourceManager.GetString("Dropdown Field 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Dropdown Field 3.
        /// </summary>
        internal static string Dropdown_Field_3 {
            get {
                return ResourceManager.GetString("Dropdown Field 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Other Field.
        /// </summary>
        internal static string Enum_Field {
            get {
                return ResourceManager.GetString("Enum Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended (probably redundant) description of Some Field, a text-based configuration.
        /// </summary>
        internal static string Example_Description {
            get {
                return ResourceManager.GetString("Example Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensión del archivo.
        /// </summary>
        internal static string File_Extension {
            get {
                return ResourceManager.GetString("File Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de entrada.
        /// </summary>
        internal static string Input_Path {
            get {
                return ResourceManager.GetString("Input Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer Field.
        /// </summary>
        internal static string Integer_Field {
            get {
                return ResourceManager.GetString("Integer Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantener logs (meses).
        /// </summary>
        internal static string Keep_Logs_For_Months {
            get {
                return ResourceManager.GetString("Keep Logs For Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Common.
        /// </summary>
        internal static string Less_Common {
            get {
                return ResourceManager.GetString("Less Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linea.
        /// </summary>
        internal static string Line_ {
            get {
                return ResourceManager.GetString("Line_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs y tiempo de respuesta.
        /// </summary>
        internal static string Logs___Time {
            get {
                return ResourceManager.GetString("Logs & Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maquina.
        /// </summary>
        internal static string Machine_ {
            get {
                return ResourceManager.GetString("Machine_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcion A.
        /// </summary>
        internal static string Option_A {
            get {
                return ResourceManager.GetString("Option A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcion  B.
        /// </summary>
        internal static string Option_B {
            get {
                return ResourceManager.GetString("Option B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcion  X.
        /// </summary>
        internal static string Option_C {
            get {
                return ResourceManager.GetString("Option C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Enum Field.
        /// </summary>
        internal static string Other_Field {
            get {
                return ResourceManager.GetString("Other Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la ruta de resplado de entrada.
        /// </summary>
        internal static string Put_Backup_Input_Path {
            get {
                return ResourceManager.GetString("Put Backup Input Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la ruta de resplado de trazabilidad.
        /// </summary>
        internal static string Put_Backup_SFC_Path {
            get {
                return ResourceManager.GetString("Put Backup SFC Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la extensión del archivo.
        /// </summary>
        internal static string Put_File_Extension {
            get {
                return ResourceManager.GetString("Put File Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la extensión del archivo de respuesta.
        /// </summary>
        internal static string Put_File_SFC_Extension {
            get {
                return ResourceManager.GetString("Put File SFC Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la ruta de entrada.
        /// </summary>
        internal static string Put_Input_Path {
            get {
                return ResourceManager.GetString("Put Input Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona cuantos meses se mantendran los logs.
        /// </summary>
        internal static string Put_Keep_Logs_For_Months {
            get {
                return ResourceManager.GetString("Put Keep Logs For Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la Linea correspondiente.
        /// </summary>
        internal static string Put_Line_ {
            get {
                return ResourceManager.GetString("Put Line_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el tipo de maquina.
        /// </summary>
        internal static string Put_Machine_ {
            get {
                return ResourceManager.GetString("Put Machine_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar modo para tarjetas de reparación?.
        /// </summary>
        internal static string Put_Repair_Boards {
            get {
                return ResourceManager.GetString("Put Repair Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar log de falla al servidor?.
        /// </summary>
        internal static string Put_Send_Repair_File {
            get {
                return ResourceManager.GetString("Put Send Repair File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la ruta de trazabilidad (SFC).
        /// </summary>
        internal static string Put_SFC_Path {
            get {
                return ResourceManager.GetString("Put SFC Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el tiempo limite de respuesta en segundos .
        /// </summary>
        internal static string Put_Sfc_Timeout {
            get {
                return ResourceManager.GetString("Put Sfc Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la estacion correspondiente.
        /// </summary>
        internal static string Put_Station_ {
            get {
                return ResourceManager.GetString("Put Station_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el tiempo para cerrar ventana Ok/Reparación.
        /// </summary>
        internal static string Put_Window_Timeout {
            get {
                return ResourceManager.GetString("Put Window Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjetas de reparación.
        /// </summary>
        internal static string Repair_Boards {
            get {
                return ResourceManager.GetString("Repair Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar archivo de reparacion (SFC)?.
        /// </summary>
        internal static string Send_Repair_File {
            get {
                return ResourceManager.GetString("Send Repair File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensión del archivo de respuesta.
        /// </summary>
        internal static string SFC_File_Extension {
            get {
                return ResourceManager.GetString("SFC File Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de trazabilidad (SFC).
        /// </summary>
        internal static string SFC_Path {
            get {
                return ResourceManager.GetString("SFC Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout para respuesta de SFC (s).
        /// </summary>
        internal static string Sfc_Timeout {
            get {
                return ResourceManager.GetString("Sfc Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string Slow {
            get {
                return ResourceManager.GetString("Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estacion.
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estacion.
        /// </summary>
        internal static string Station_ {
            get {
                return ResourceManager.GetString("Station_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Text FielD.
        /// </summary>
        internal static string Text_Field {
            get {
                return ResourceManager.GetString("Text Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay para cerrar ventana Ok/Reparación.
        /// </summary>
        internal static string Window_Timeout {
            get {
                return ResourceManager.GetString("Window Timeout", resourceCulture);
            }
        }
    }
}
